//! `nexus-probe` library — host enumeration + config generation.
//!
//! The companion CLI (`crates/nexus-probe/src/main.rs`) builds a
//! [`Manifest`] (serialized to `device-manifest.json`) and, via
//! `emit-config`, generates a complete capability-based `nexus.toml`
//! from the detected hardware.
//!
//! Wire shape is stable: changing serde field names / order is a
//! breaking change for `device-manifest.json` consumers.

use std::collections::HashSet;
use std::fs;
use std::process::Command;

use chrono::Utc;
use serde::{Deserialize, Serialize};

pub mod generate;
pub mod profile;

pub use generate::{generate_config, render_toml};
pub use profile::{DecodeCapability, ForcedProfile, HardwareProfile, InferenceDevice};

// ---------------------------------------------------------------------------
// Wire types — exposed so external callers (engine + tests) can consume them.
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Manifest {
    pub schema: u32,
    pub captured_at: String,
    pub host: HostInfo,
    pub cpu: CpuInfo,
    pub memory: MemoryInfo,
    pub accelerators: Accelerators,
    pub runtimes: Runtimes,
    /// Recommended capability profile (`intel-igpu` / `intel-npu` / `hailo` /
    /// `amd-rocm` / `amd-vulkan` / `nvidia` / `cpu` / `dev`) derived from the
    /// detected CPU + accelerators. See docs/HARDWARE_MATRIX.md for the
    /// mapping. Advisory label retained for cloud observability; the live
    /// nexus.toml is generated by `emit-config`, not selected by this label.
    pub recommended_profile: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct HostInfo {
    pub hostname: String,
    pub os: String,
    pub arch: String,
    pub kernel: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CpuInfo {
    pub model_name: String,
    pub physical_cores: usize,
    pub logical_cores: usize,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct MemoryInfo {
    pub total_kib: u64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Accelerators {
    pub intel_igpu: bool,
    /// A discrete Intel Arc A-series (DG2) GPU is present. Folded into the
    /// Intel-GPU profile decision alongside `intel_igpu`; the field name is
    /// retained for `device-manifest.json` wire stability.
    pub intel_arc_140v: bool,
    pub intel_npu: bool,
    pub nvidia_gpu: bool,
    /// Total VRAM of NVIDIA GPU 0 in MiB, read from `nvidia-smi`. `None`
    /// when no NVIDIA card is present, or when the proprietary driver is
    /// not yet live (`nvidia-smi` missing or erroring) — which is also the
    /// state on a box awaiting the post-driver-install reboot. Consumers
    /// treat `None` as "unknown" and under-provision rather than guess.
    ///
    /// GPU 0 specifically, because that is the device the CUDA execution
    /// provider binds by default (see `cuda_device_id` in
    /// `nexus-inference`).
    #[serde(default)]
    pub nvidia_vram_mib: Option<u64>,
    pub apple_silicon: bool,
    /// AMD Radeon iGPU (Phoenix-class Ryzen 7000/8000 APUs) or any
    /// AMD dGPU. Used for hardware H.264/HEVC decode via VA-API
    /// (Mesa Gallium). Inference EP for AMD is not wired today —
    /// ROCm on Phoenix gfx1035 is an experimental spike.
    pub amd_igpu: bool,
    /// Hailo-8 / Hailo-8L M.2 accelerator (PCI vendor 0x1e60).
    /// A Hailo present recommends the `hailo` capability profile.
    /// Until `M_HAILO_EP` lands the engine still falls back to the
    /// CPU EP at runtime — the detection is what unlocks the
    /// auto-profile mapping ahead of the EP work.
    pub hailo: bool,
    /// True only when an AMD GPU whose PCI device ID is on the
    /// ROCm-supported allowlist (discrete CDNA / RDNA2 / RDNA3) is
    /// present. Default-deny: Phoenix / Rembrandt iGPUs (gfx1035 /
    /// gfx1103) and any unvetted part stay `false` and route to the
    /// Vulkan EP. Ported from `scripts/lib/install-common.sh`
    /// (`_ROCM_SUPPORTED_PCI_IDS`) so the ROCm-vs-Vulkan EP decision
    /// lives in exactly one place. `#[serde(default)]` keeps older
    /// `device-manifest.json` (which lacks this key) deserializable.
    #[serde(default)]
    pub amd_rocm_capable: bool,
    pub render_nodes: Vec<String>,
    pub accel_nodes: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Runtimes {
    pub gstreamer: Option<String>,
    pub onnxruntime: Option<String>,
    pub docker: Option<String>,
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Probe the host and assemble a fresh [`Manifest`]. This is the single
/// entry point used by the CLI binary for both `device-manifest.json`
/// emission and `emit-config` capability-based config generation.
pub fn build_manifest() -> Manifest {
    let host = probe_host();
    let cpu = probe_cpu();
    let memory = probe_memory();
    let accelerators = probe_accelerators();
    let runtimes = probe_runtimes();
    let recommended_profile = recommend_profile(&cpu, &accelerators);
    Manifest {
        schema: 1,
        captured_at: Utc::now().to_rfc3339(),
        host,
        cpu,
        memory,
        accelerators,
        runtimes,
        recommended_profile: recommended_profile.into(),
    }
}

/// Install-time accelerator tags for a host, in the vocabulary the
/// installer's driver-selection logic consumes (`intel-igpu`,
/// `intel-arc-dgpu`, `intel-npu`, `nvidia-gpu`, `amd-igpu`, `hailo-m2`)
/// plus the ROCm-vs-Vulkan verdict. Emitted by `nexus-probe accel-tags`
/// so the installer no longer duplicates the `lspci` scan or the ROCm
/// device-ID allowlist — detection lives only here.
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct AccelTags {
    /// One entry per detected accelerator class. Stable vocabulary shared
    /// with `scripts/lib/install-common.sh`.
    pub tags: Vec<String>,
    /// True when a discrete AMD GPU on the ROCm allowlist is present;
    /// drives the installer's ROCm-vs-Vulkan driver/EP choice.
    pub amd_rocm_capable: bool,
}

/// Probe the host and produce its [`AccelTags`]. Shares the single
/// `lspci -nn` detector ([`detect_accel_from_lspci`]) with
/// [`build_manifest`], so the installer's driver selection and the
/// generated `nexus.toml` always agree about the box's hardware.
pub fn accel_tags() -> AccelTags {
    let lspci = shell_out("lspci", &["-nn"]).unwrap_or_default();
    let det = detect_accel_from_lspci(&lspci);
    let accel_nodes = list_dir_starts_with("/dev/accel", "");
    let mut tags = Vec::new();
    if det.intel_igpu {
        tags.push("intel-igpu".to_string());
    }
    if det.intel_arc_dgpu {
        tags.push("intel-arc-dgpu".to_string());
    }
    if det.intel_npu || !accel_nodes.is_empty() {
        tags.push("intel-npu".to_string());
    }
    if det.nvidia_gpu {
        tags.push("nvidia-gpu".to_string());
    }
    if det.amd_igpu {
        tags.push("amd-igpu".to_string());
    }
    if det.hailo {
        tags.push("hailo-m2".to_string());
    }
    AccelTags {
        tags,
        amd_rocm_capable: detect_amd_rocm_capable(),
    }
}

// ---------------------------------------------------------------------------
// Probe helpers
// ---------------------------------------------------------------------------

fn probe_host() -> HostInfo {
    HostInfo {
        hostname: hostname_or("unknown"),
        os: std::env::consts::OS.into(),
        arch: std::env::consts::ARCH.into(),
        kernel: shell_out("uname", &["-r"]).unwrap_or_default(),
    }
}

fn hostname_or(default: &str) -> String {
    shell_out("hostname", &[]).unwrap_or_else(|| default.into())
}

fn probe_cpu() -> CpuInfo {
    let model = read_first_field("/proc/cpuinfo", "model name").unwrap_or_default();
    let logical = std::thread::available_parallelism()
        .map(|n| n.get())
        .unwrap_or(0);
    // Physical: count unique "physical id"s on Linux; on other OS just use logical.
    let physical = if cfg!(target_os = "linux") {
        count_unique_field("/proc/cpuinfo", "physical id").unwrap_or(logical)
    } else {
        logical
    };
    CpuInfo {
        model_name: model,
        physical_cores: physical,
        logical_cores: logical,
    }
}

fn probe_memory() -> MemoryInfo {
    let total = read_first_field("/proc/meminfo", "MemTotal")
        .and_then(|s| {
            s.split_whitespace()
                .next()
                .and_then(|x| x.parse::<u64>().ok())
        })
        .unwrap_or(0);
    MemoryInfo { total_kib: total }
}

fn probe_accelerators() -> Accelerators {
    let lspci = shell_out("lspci", &["-nn"]).unwrap_or_default();
    let det = detect_accel_from_lspci(&lspci);
    let render_nodes = list_dir_starts_with("/dev/dri", "renderD");
    let accel_nodes = list_dir_starts_with("/dev/accel", "");
    Accelerators {
        intel_igpu: det.intel_igpu,
        intel_arc_140v: det.intel_arc_dgpu,
        // A /dev/accel node is a runtime signal an NPU exists even when
        // lspci can't name it; keep it as an additional positive.
        intel_npu: det.intel_npu || !accel_nodes.is_empty(),
        nvidia_gpu: det.nvidia_gpu,
        nvidia_vram_mib: if det.nvidia_gpu {
            probe_nvidia_vram_mib()
        } else {
            None
        },
        apple_silicon: cfg!(all(target_os = "macos", target_arch = "aarch64")),
        amd_igpu: det.amd_igpu,
        hailo: det.hailo,
        // ROCm-vs-Vulkan: read PCI device IDs from sysfs and match the
        // allowlist (default-deny). Linux-only; false elsewhere.
        amd_rocm_capable: detect_amd_rocm_capable(),
        render_nodes,
        accel_nodes,
    }
}

/// Total VRAM of NVIDIA GPU 0, in MiB, via `nvidia-smi`.
///
/// Returns `None` whenever the answer is not trustworthy: no driver, an
/// erroring `nvidia-smi`, or unparseable output. Callers under-provision
/// on `None` rather than guessing.
///
/// The installer runs `install_drivers` before `emit-config`, so by the
/// time the generated `nexus.toml` is written the driver is live and this
/// answers. When the driver install demands a reboot the installer exits
/// before generating a config at all, and the post-reboot re-run probes a
/// working driver.
fn probe_nvidia_vram_mib() -> Option<u64> {
    let out = shell_out(
        "nvidia-smi",
        &[
            "--query-gpu=memory.total",
            "--format=csv,noheader,nounits",
            "--id=0",
        ],
    )?;
    parse_nvidia_smi_vram_mib(&out)
}

/// Parse `nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits`
/// output (a bare MiB integer per GPU) into the first GPU's VRAM.
///
/// Rejects zero, which `nvidia-smi` reports for a GPU in an error state
/// and which would otherwise bucket as an absurdly small card.
fn parse_nvidia_smi_vram_mib(out: &str) -> Option<u64> {
    out.lines()
        .map(str::trim)
        .find(|l| !l.is_empty())
        .and_then(|l| l.parse::<u64>().ok())
        .filter(|mib| *mib > 0)
}

/// Accelerator presence derived from a single pass over `lspci -nn`. The
/// one detector shared by [`build_manifest`] (→ `device-manifest.json` /
/// `emit-config`) and [`accel_tags`] (→ the installer's driver
/// selection), so the generated `nexus.toml` and the drivers actually
/// installed can never disagree about what hardware is present.
#[derive(Debug, Default, Clone, Copy)]
struct AccelDetection {
    intel_igpu: bool,
    intel_arc_dgpu: bool,
    intel_npu: bool,
    nvidia_gpu: bool,
    amd_igpu: bool,
    hailo: bool,
}

/// Parse `lspci -nn` output into [`AccelDetection`]. Device-ID-precise,
/// matching the vocabulary the installer historically detected in bash
/// (`scripts/lib/install-common.sh`), so moving detection here does not
/// regress driver selection. Each rule is applied per line (as `grep`
/// would), then OR-ed across the device list.
fn detect_accel_from_lspci(lspci_nn: &str) -> AccelDetection {
    let mut d = AccelDetection::default();
    for line in lspci_nn.lines() {
        let lower = line.to_ascii_lowercase();
        // Intel iGPU/dGPU: display-class VGA with vendor 8086 (covers
        // UHD, Iris Xe, Arc 140V, and discrete Arc — the latter is also
        // tagged below).
        if line.contains("VGA") && line.contains("[8086:") {
            d.intel_igpu = true;
        }
        // Intel Arc A-series discrete (DG2 silicon): device IDs 56a0..56af.
        if line_has_arc_dgpu(line) {
            d.intel_arc_dgpu = true;
        }
        // Intel NPU: Meteor Lake (7d1d), Arrow Lake (643e), Lunar Lake
        // (7e4e), or the "Processing accelerators" PCI class for a future
        // SKU the device-ID list misses.
        if line.contains("[8086:7d1d]")
            || line.contains("[8086:643e]")
            || line.contains("[8086:7e4e]")
            || (lower.contains("processing accelerator") && lower.contains("[8086:"))
        {
            d.intel_npu = true;
        }
        // NVIDIA discrete (vendor 10de).
        if (line.contains("VGA") || line.contains("3D controller")) && line.contains("[10de:") {
            d.nvidia_gpu = true;
        }
        // AMD iGPU/dGPU (vendor 1002): Radeon 680M/780M iGPUs and any dGPU.
        if (line.contains("VGA")
            || line.contains("3D controller")
            || line.contains("Display controller"))
            && line.contains("[1002:")
        {
            d.amd_igpu = true;
        }
        // Hailo-8 / Hailo-8L M.2 accelerator (vendor 1e60).
        if line.contains("[1e60:") {
            d.hailo = true;
        }
    }
    d
}

/// True when `line` carries an Intel Arc A-series discrete device ID
/// (`[8086:56XY]` with `X` in `a..=f`), i.e. the bash
/// `\[8086:56[a-f][0-9a-f]\]` match. Implemented without a regex
/// dependency.
fn line_has_arc_dgpu(line: &str) -> bool {
    for (idx, _) in line.match_indices("[8086:56") {
        let rest = &line[idx + "[8086:56".len()..];
        let mut chars = rest.chars();
        if let (Some(a), Some(b), Some(']')) = (chars.next(), chars.next(), chars.next()) {
            if matches!(a, 'a'..='f' | 'A'..='F') && b.is_ascii_hexdigit() {
                return true;
            }
        }
    }
    false
}

/// Static allowlist of AMD PCI device IDs (the `XXXX` in `1002:XXXX`) that
/// ROCm OFFICIALLY supports: discrete RDNA2 (gfx1030), RDNA3
/// (gfx1100/1101/1102), and CDNA (gfx908/gfx90a/gfx942). This is the
/// single source of truth for the ROCm-vs-Vulkan decision; the bash
/// installer queries it via `nexus-probe accel-tags` (the duplicate
/// `_ROCM_SUPPORTED_PCI_IDS` array was removed). Deliberately
/// DEFAULT-DENY: anything NOT listed (Phoenix / Rembrandt iGPUs gfx1035
/// / gfx1103, unvetted or brand-new parts) routes to the Vulkan(WebGPU)
/// EP, never ROCm.
const ROCM_SUPPORTED_PCI_IDS: &[&str] = &[
    // CDNA — MI100 (gfx908)
    "738c", "738e", //
    // CDNA2 — MI200 / MI210 / MI250 (gfx90a)
    "7408", "740c", "740f", "7410", //
    // CDNA3 — MI300 (gfx942)
    "74a0", "74a1", "74a5", "74a9", "74b5", "74b9", "74bd", //
    // RDNA2 — Navi 21, RX 6800/6900 (gfx1030)
    "73a1", "73a2", "73a3", "73a5", "73ab", "73af", "73bf", //
    // RDNA3 — Navi 31 RX 7900 (gfx1100), Navi 32 RX 7700/7800 (gfx1101),
    // Navi 33 RX 7600 (gfx1102)
    "744c", "745e", "747e", "7480", "7483",
];

/// Pure allowlist check: true when `device_id` — the `device` portion of
/// `1002:device` (with or without a `0x` prefix, any case) — is a
/// ROCm-supported part. The pure half of the ROCm-vs-Vulkan classifier so
/// it can be unit-tested without sysfs.
fn amd_rocm_supported(device_id: &str) -> bool {
    let id = device_id
        .trim()
        .trim_start_matches("0x")
        .to_ascii_lowercase();
    ROCM_SUPPORTED_PCI_IDS.contains(&id.as_str())
}

/// Best-effort sysfs scan for an AMD GPU whose PCI device ID is on the
/// ROCm allowlist. Mirrors the PRIMARY classifier in the bash
/// `_amd_gpu_rocm_supported`: iterate `/sys/class/drm/card*/device`, keep
/// AMD vendor `0x1002` nodes, match the `device` ID against the allowlist.
/// Linux-only — on macOS (and any host without sysfs) `read_dir` fails and
/// this returns `false`, failing safe to the Vulkan EP. The bash helper's
/// SECONDARY `rocminfo` gfx probe stays installer-side (it only matters
/// when ROCm is already installed); the sysfs allowlist is authoritative
/// for the manifest.
fn detect_amd_rocm_capable() -> bool {
    let Ok(rd) = fs::read_dir("/sys/class/drm") else {
        return false;
    };
    for ent in rd.flatten() {
        let name = ent.file_name().to_string_lossy().to_string();
        if !name.starts_with("card") {
            continue;
        }
        let dev = ent.path().join("device");
        let Ok(vendor) = fs::read_to_string(dev.join("vendor")) else {
            continue;
        };
        if vendor.trim() != "0x1002" {
            continue; // AMD/ATI only
        }
        let Ok(device) = fs::read_to_string(dev.join("device")) else {
            continue;
        };
        if amd_rocm_supported(device.trim()) {
            return true;
        }
    }
    false
}

fn probe_runtimes() -> Runtimes {
    Runtimes {
        gstreamer: shell_out("gst-launch-1.0", &["--version"])
            .and_then(|s| s.lines().next().map(|l| l.to_string())),
        onnxruntime: detect_onnxruntime(),
        docker: shell_out("docker", &["--version"]),
    }
}

fn detect_onnxruntime() -> Option<String> {
    for p in [
        "/usr/local/lib/libonnxruntime.so",
        "/opt/onnxruntime/lib/libonnxruntime.so",
    ] {
        if std::path::Path::new(p).exists() {
            return Some(p.into());
        }
    }
    None
}

/// Map detected hardware to one of the capability-profile labels the edge
/// reports and the installer's `--force-profile` flag accepts (`intel-igpu`,
/// `intel-npu`, `hailo`, `amd-rocm`, `amd-vulkan`, `nvidia`, `cpu`, `dev`).
/// Mirrors the matrix in docs/HARDWARE_MATRIX.md — keep them in sync. The
/// label is advisory; the live config comes from `emit-config`.
fn recommend_profile(cpu: &CpuInfo, acc: &Accelerators) -> &'static str {
    let model = cpu.model_name.to_lowercase();
    if acc.nvidia_gpu {
        return "nvidia";
    }
    // EQR7 + Hailo-8 SKU. Detected by Hailo presence alone — regardless of
    // which AMD/Intel host CPU drives it. Engine still falls back to CPU EP
    // at runtime until M_HAILO_EP ships.
    if acc.hailo {
        return "hailo";
    }
    // Lunar Lake = Core Ultra 7 256V (Arc 140V iGPU + NPU 4).
    if acc.intel_arc_140v
        || acc.intel_npu
        || model.contains("core ultra 7 256v")
        || model.contains("core ultra 9 288v")
        || model.contains("lunar lake")
    {
        return "intel-npu";
    }
    // Discrete Arc (A310/A380/A580/A750/A770), Iris Xe, and UHD (N-series)
    // iGPUs all run the Intel GPU (OpenVINO) EP.
    if model.contains("arc a3") || model.contains("arc a5") || model.contains("arc a7") {
        return "intel-igpu";
    }
    if model.contains("i7-12700h") || model.contains("iris xe") || model.contains("96 eu") {
        return "intel-igpu";
    }
    if model.contains("n100")
        || model.contains("n150")
        || model.contains("n200")
        || model.contains("n305")
    {
        return "intel-igpu";
    }
    if acc.apple_silicon {
        return "dev";
    }
    // AMD-only (Radeon iGPU/dGPU, no Hailo): ROCm-capable discrete parts run
    // the ROCm EP; everything else routes to the Vulkan (WebGPU) EP.
    if acc.amd_rocm_capable {
        return "amd-rocm";
    }
    if acc.amd_igpu {
        return "amd-vulkan";
    }
    // Any remaining Intel iGPU not matched by model string.
    if acc.intel_igpu {
        return "intel-igpu";
    }
    // Fallback: no recognised accelerator — CPU EP.
    "cpu"
}

// ---------------------------------------------------------------------------
// Generic helpers
// ---------------------------------------------------------------------------

fn shell_out(cmd: &str, args: &[&str]) -> Option<String> {
    let out = Command::new(cmd).args(args).output().ok()?;
    if !out.status.success() {
        return None;
    }
    Some(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn read_first_field(path: &str, key: &str) -> Option<String> {
    let txt = std::fs::read_to_string(path).ok()?;
    for line in txt.lines() {
        if let Some((k, v)) = line.split_once(':') {
            if k.trim() == key {
                return Some(v.trim().to_string());
            }
        }
    }
    None
}

fn count_unique_field(path: &str, key: &str) -> Option<usize> {
    let txt = std::fs::read_to_string(path).ok()?;
    let mut seen = HashSet::new();
    for line in txt.lines() {
        if let Some((k, v)) = line.split_once(':') {
            if k.trim() == key {
                seen.insert(v.trim().to_string());
            }
        }
    }
    Some(seen.len().max(1))
}

fn list_dir_starts_with(path: &str, prefix: &str) -> Vec<String> {
    let mut out = Vec::new();
    let Ok(rd) = fs::read_dir(path) else {
        return out;
    };
    for ent in rd.flatten() {
        let name = ent.file_name().to_string_lossy().to_string();
        if name.starts_with(prefix) {
            out.push(format!("{}/{}", path, name));
        }
    }
    out.sort();
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn nvidia_wins_over_everything() {
        let cpu = CpuInfo {
            model_name: "Intel(R) Core(TM) i7-12700H".into(),
            physical_cores: 6,
            logical_cores: 12,
        };
        let acc = Accelerators {
            nvidia_gpu: true,
            intel_igpu: true,
            ..Default::default()
        };
        assert_eq!(recommend_profile(&cpu, &acc), "nvidia");
    }

    #[test]
    fn lunar_lake_via_npu_node() {
        let cpu = CpuInfo {
            model_name: "Intel(R) Core(TM) Ultra 7 256V".into(),
            ..Default::default()
        };
        let acc = Accelerators {
            intel_npu: true,
            accel_nodes: vec!["/dev/accel/accel0".into()],
            ..Default::default()
        };
        assert_eq!(recommend_profile(&cpu, &acc), "intel-npu");
    }

    #[test]
    fn discrete_arc_is_intel_igpu() {
        // The branch matches a literal "arc a3" / "arc a5" / "arc a7"
        // substring (with the space). Trademark markers like
        // "Arc(TM) A380" disqualify the model string; this is a
        // pre-existing probe limitation worth pinning so it doesn't
        // silently regress when someone refactors `recommend_profile`.
        let cpu = CpuInfo {
            model_name: "Intel Arc A380 Graphics".into(),
            ..Default::default()
        };
        let acc = Accelerators::default();
        assert_eq!(recommend_profile(&cpu, &acc), "intel-igpu");
    }

    #[test]
    fn iris_xe_is_intel_igpu() {
        let cpu = CpuInfo {
            model_name: "12th Gen Intel(R) Core(TM) i7-12700H".into(),
            ..Default::default()
        };
        let acc = Accelerators::default();
        assert_eq!(recommend_profile(&cpu, &acc), "intel-igpu");
    }

    #[test]
    fn hailo_present_is_hailo() {
        // EQR7 + Hailo-8 SKU: Hailo flag set on a Ryzen host. `hailo`
        // should win regardless of the AMD iGPU also being detected.
        let cpu = CpuInfo {
            model_name: "AMD Ryzen 7 7735HS with Radeon Graphics".into(),
            ..Default::default()
        };
        let acc = Accelerators {
            hailo: true,
            amd_igpu: true,
            ..Default::default()
        };
        assert_eq!(recommend_profile(&cpu, &acc), "hailo");
    }

    #[test]
    fn amd_rocm_capable_is_amd_rocm() {
        // Discrete ROCm-supported AMD part → the ROCm EP profile.
        let cpu = CpuInfo {
            model_name: "AMD Ryzen 9".into(),
            ..Default::default()
        };
        let acc = Accelerators {
            amd_igpu: true,
            amd_rocm_capable: true,
            ..Default::default()
        };
        assert_eq!(recommend_profile(&cpu, &acc), "amd-rocm");
    }

    #[test]
    fn amd_only_is_amd_vulkan() {
        // Bare AMD APU with no Hailo and not ROCm-allowlisted: routes to
        // the Vulkan (WebGPU) EP. Decode path still works via Mesa VA-API.
        let cpu = CpuInfo {
            model_name: "AMD Ryzen 7 7735HS with Radeon Graphics".into(),
            ..Default::default()
        };
        let acc = Accelerators {
            amd_igpu: true,
            ..Default::default()
        };
        assert_eq!(recommend_profile(&cpu, &acc), "amd-vulkan");
    }

    #[test]
    fn nvidia_wins_over_hailo() {
        // Defensive: if a future SKU ever pairs an NVIDIA dGPU with
        // a Hailo M.2 (unlikely but not impossible) we want `nvidia` to
        // win — that's where the CUDA EP actually attaches.
        let cpu = CpuInfo {
            model_name: "AMD Ryzen 9".into(),
            ..Default::default()
        };
        let acc = Accelerators {
            nvidia_gpu: true,
            hailo: true,
            ..Default::default()
        };
        assert_eq!(recommend_profile(&cpu, &acc), "nvidia");
    }

    #[test]
    fn n_series_is_intel_igpu() {
        let cpu = CpuInfo {
            model_name: "Intel(R) N150".into(),
            ..Default::default()
        };
        let acc = Accelerators::default();
        assert_eq!(recommend_profile(&cpu, &acc), "intel-igpu");
    }

    #[test]
    fn apple_silicon_fallback_is_dev() {
        let cpu = CpuInfo {
            model_name: "Apple M2 Pro".into(),
            ..Default::default()
        };
        let acc = Accelerators {
            apple_silicon: true,
            ..Default::default()
        };
        assert_eq!(recommend_profile(&cpu, &acc), "dev");
    }

    #[test]
    fn unknown_falls_back_to_cpu() {
        let cpu = CpuInfo {
            model_name: "Some Future Chip 9000".into(),
            ..Default::default()
        };
        let acc = Accelerators::default();
        assert_eq!(recommend_profile(&cpu, &acc), "cpu");
    }

    #[test]
    fn manifest_serializes_with_stable_field_names() {
        // Wire-compat regression: device-manifest.json consumers depend
        // on these top-level keys staying as-is.
        let m = Manifest::default();
        let v = serde_json::to_value(&m).expect("serialize");
        for key in [
            "schema",
            "captured_at",
            "host",
            "cpu",
            "memory",
            "accelerators",
            "runtimes",
            "recommended_profile",
        ] {
            assert!(v.get(key).is_some(), "missing top-level key {key}");
        }
    }

    #[test]
    fn rocm_allowlist_accepts_supported_discrete_parts() {
        // One representative per family that the bash allowlist covers.
        for id in ["738c", "7410", "74a0", "73a5", "744c", "7483"] {
            assert!(amd_rocm_supported(id), "{id} should be ROCm-supported");
        }
    }

    #[test]
    fn rocm_allowlist_normalizes_prefix_and_case() {
        // sysfs reports e.g. "0x744C\n"; the matcher must strip 0x, trim,
        // and lowercase before comparing.
        assert!(amd_rocm_supported("0x744C"));
        assert!(amd_rocm_supported("  744C  "));
    }

    #[test]
    fn rocm_allowlist_default_denies_igpus_and_unknowns() {
        // Phoenix 780M (0x15bf, gfx1103) and Rembrandt 680M (0x1681,
        // gfx1035) are iGPUs that must route to Vulkan, never ROCm.
        // An arbitrary unvetted ID is denied too.
        for id in ["15bf", "1681", "1900", "ffff"] {
            assert!(!amd_rocm_supported(id), "{id} must NOT be ROCm-supported");
        }
    }

    #[test]
    fn accelerators_amd_rocm_capable_deserializes_from_legacy_manifest() {
        // Wire-compat: an older device-manifest.json that predates the
        // amd_rocm_capable key must still deserialize (serde default
        // -> false), never error.
        let json = r#"{
            "intel_igpu": false,
            "intel_arc_140v": false,
            "intel_npu": false,
            "nvidia_gpu": false,
            "apple_silicon": false,
            "amd_igpu": true,
            "hailo": false,
            "render_nodes": [],
            "accel_nodes": []
        }"#;
        let acc: Accelerators = serde_json::from_str(json).expect("legacy accelerators parse");
        assert!(acc.amd_igpu);
        assert!(!acc.amd_rocm_capable);
    }

    #[test]
    fn lspci_detects_intel_igpu_only() {
        let s = "00:02.0 VGA compatible controller [0300]: Intel Corporation \
                 Alder Lake-N [UHD Graphics] [8086:46d1]";
        let d = detect_accel_from_lspci(s);
        assert!(d.intel_igpu);
        assert!(!d.intel_arc_dgpu);
        assert!(!d.intel_npu && !d.nvidia_gpu && !d.amd_igpu && !d.hailo);
    }

    #[test]
    fn lspci_detects_arc_dgpu_alongside_igpu() {
        let s = "00:02.0 VGA compatible controller [0300]: Intel Corporation \
                 Raptor Lake-S UHD Graphics [8086:a780]\n\
                 03:00.0 VGA compatible controller [0300]: Intel Corporation \
                 DG2 [Arc A380] [8086:56a5]";
        let d = detect_accel_from_lspci(s);
        assert!(d.intel_igpu);
        assert!(d.intel_arc_dgpu);
    }

    #[test]
    fn lspci_arc_dgpu_rejects_non_arc_8086_ids() {
        // a780 (RPL iGPU) is not in the 56xx Arc range.
        assert!(!detect_accel_from_lspci("VGA ... [8086:a780]").intel_arc_dgpu);
        // 5690: third char '9' is not in a..f, so not an Arc dGPU.
        assert!(!detect_accel_from_lspci("VGA ... [8086:5690]").intel_arc_dgpu);
    }

    #[test]
    fn nvidia_smi_vram_parses_first_gpu() {
        // `--format=csv,noheader,nounits` emits a bare MiB integer per GPU.
        assert_eq!(parse_nvidia_smi_vram_mib("5059\n"), Some(5059));
        // Multi-GPU: GPU 0 wins, matching the CUDA EP's default device.
        assert_eq!(parse_nvidia_smi_vram_mib("8192\n24576\n"), Some(8192));
        assert_eq!(parse_nvidia_smi_vram_mib("  12288  "), Some(12288));
    }

    #[test]
    fn nvidia_smi_vram_rejects_untrustworthy_output() {
        assert_eq!(parse_nvidia_smi_vram_mib(""), None);
        // A GPU in an error state reports 0 — never a real bucket.
        assert_eq!(parse_nvidia_smi_vram_mib("0\n"), None);
        // Header row (a missing `noheader`) must not parse as a size.
        assert_eq!(parse_nvidia_smi_vram_mib("memory.total [MiB]\n"), None);
        // Units left in (a missing `nounits`) must not silently truncate.
        assert_eq!(parse_nvidia_smi_vram_mib("5059 MiB\n"), None);
    }

    #[test]
    fn lspci_detects_intel_npu_by_device_id_and_class() {
        let by_id = "00:0b.0 Processing accelerators [1200]: Intel Corporation \
                     Meteor Lake NPU [8086:7d1d]";
        assert!(detect_accel_from_lspci(by_id).intel_npu);
        // Class-based fallback for an unlisted future device id.
        let by_class = "00:0b.0 Processing accelerators [1200]: Intel Corporation \
                        Future NPU [8086:1234]";
        assert!(detect_accel_from_lspci(by_class).intel_npu);
    }

    #[test]
    fn lspci_detects_nvidia_amd_hailo() {
        let nv = "01:00.0 VGA compatible controller [0300]: NVIDIA Corporation \
                  GA106 [GeForce RTX 3060] [10de:2503]";
        assert!(detect_accel_from_lspci(nv).nvidia_gpu);
        let amd = "06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, \
                   Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681]";
        assert!(detect_accel_from_lspci(amd).amd_igpu);
        let hailo = "01:00.0 Co-processor [0b40]: Hailo Technologies Ltd. \
                     Hailo-8 AI Processor [1e60:2864]";
        assert!(detect_accel_from_lspci(hailo).hailo);
    }

    #[test]
    fn lspci_ignores_non_gpu_amd_chipset_devices() {
        // AMD CPU-vendor (1022) SMBus/PCI bridges must not trip amd_igpu;
        // the GPU vendor is 1002 and the rule needs a display device class.
        let s = "00:14.0 SMBus [0c05]: Advanced Micro Devices, Inc. [AMD/ATI] \
                 FCH SMBus Controller [1022:790b]";
        assert!(!detect_accel_from_lspci(s).amd_igpu);
    }
}
