// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Video codec carried by a camera's RTSP stream.
 *
 * The `_plus` variants are operator-selected labels for vendor SVC
 * configurations (Hikvision H.264+/H.265+, Dahua Smart Codec, Uniview
 * U-Code). Autodetect (ONVIF / SDP) never produces a `_plus` variant —
 * SVC is wire-compatible with the base codec, so the depayloader,
 * parser, and decoder are identical. `.base()` collapses to the wire
 * label the cloud and the pipeline care about (`"h264"` or `"h265"`).
 */
export type CodecKind = "h264" | "h264_plus" | "h265" | "h265_plus";
