// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the edge admin API resolved a camera's codec. Returned on
 * create/update responses so the UI can surface a warning banner when
 * autodetect failed and we fell back to a default.
 */
export type CodecSource = "operator" | "autodetect" | "default_fallback";
