// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";
import type { FireSmokeKind } from "./FireSmokeKind";

/**
 * A persisted fire or smoke signal from the dedicated head. Carries a
 * bounding **region** (where the texture/flicker was seen) and a
 * confidence, not a labelled object. Emitted only after the head's
 * persistence window has been satisfied (fire ≥ 2 s; smoke ≥ 5 s with a
 * growing region), so a single-frame flicker never produces one.
 */
export type FireSmokeSignal = { camera_id: bigint, kind: FireSmokeKind, 
/**
 * The region the confidence map peaked in.
 */
region: BBox, 
/**
 * Peak confidence over the persistence window, 0..1.
 */
confidence: number, 
/**
 * Wall-clock (ms since UNIX epoch) the candidate was first nominated.
 */
first_seen_unix_ms: bigint, 
/**
 * Wall-clock (ms since UNIX epoch) the persistence window was met and
 * the signal emitted.
 */
emitted_unix_ms: bigint, };
