// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackLite } from "./TrackLite";

/**
 * M_PERF_CROWD F1 — bandwidth-relief lite companion to
 * [`FrameMetadata`]. Carries only the fields the high-rate live
 * overlay needs (bbox, label, confidence, lifecycle); drops the
 * per-object `attributes` map (~400–600 bytes/object) which the
 * attributes panel still gets from the full topic. Published on
 * `topic::FRAME_METADATA_LITE` in parallel with the full topic; the
 * default SSE subscriber receives this, `?attributes=full` opts in.
 */
export type FrameMetadataLite = { camera_id: bigint, frame_id: bigint, captured_at: string, width: number, height: number, trace_id: string, 
/**
 * M_PERF_CROWD D1 — same `Arc` rationale as
 * [`FrameMetadata::objects`]. Built per-frame in the supervisor;
 * kept behind an `Arc` so the broadcast clone is a refcount bump.
 */
objects: Array<TrackLite>, };
