// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which transport carries the HD (solo / expanded) live-view video for a
 * core. Selected per-core by the cloud fleet setting `live-view.hd_transport`
 * and pushed to the edge, where it is persisted in
 * `engine_runtime_settings.hd_transport`, read live by the publisher selector,
 * and advertised in the heartbeat `caps`. The always-on LBR grid wall is
 * independent of this choice.
 *
 * * `Sfu` — WebRTC through the Cloudflare Realtime SFU (+ TURN). Talk-down
 *   audio rides the same SFU session.
 * * `Moq` — Media over QUIC relay for video; talk-down keeps a WebRTC/Opus
 *   path.
 */
export type HdTransport = "sfu" | "moq";
