// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One discrete interaction act emitted by the per-track FSM in
 * `nexus-tracker::annotator`. Serde/TS representation is the snake_case
 * token string the wire and cloud reason over.
 */
export type InteractionToken = "loiter" | "casing" | "reach_in" | "grab" | "tamper" | "remove_anchor" | "tool_proximity" | "group_form" | "group_disperse";
