// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionToken } from "./InteractionToken";

/**
 * A single emitted interaction token, keyed to a track (and, when reid
 * has assigned one, the pseudonymous per-core `entity_local_id`). The
 * payload carries **no** personal identifier per ADR-042 / R7.
 */
export type InteractionTokenEvent = { 
/**
 * The tracker's per-camera track id the token was derived from.
 */
track_id: bigint, 
/**
 * Pseudonymous per-core entity id, when reid has assigned one.
 */
entity_local_id?: string, 
/**
 * The act this token names.
 */
token: InteractionToken, 
/**
 * Wall-clock (ms since UNIX epoch) at which the FSM emitted it.
 */
emitted_unix_ms: bigint, };
