// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-camera resolved label space. Reports what is **baked**, not the
 * configured prompt subset (which may name terms the graph does not
 * carry — a silent no-op per ADR-055).
 */
export type LabelSpaceReport = { camera_id: bigint, 
/**
 * The resolved model identifier (the concrete graph in use).
 */
model_id: string, 
/**
 * The autonomy-ladder rung the resolved model sits at (its input
 * shape, e.g. `1024x576`).
 */
ladder_rung: string, 
/**
 * Open-vocab terms actually baked into the resolved graph, sorted and
 * de-duplicated for a stable, idempotent report.
 */
baked_open_vocab: Array<string>, 
/**
 * Closed-vocab namespaced labels the resolved graph emits, sorted.
 */
closed_vocab: Array<string>, };
