// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";
import type { TamperMode } from "./TamperMode";

/**
 * A place-keyed tamper signal. Carries a camera and a region and **no
 * entity** — there is no track to attribute a tampered camera to. Always
 * `never_benign`.
 */
export type TamperSignal = { camera_id: bigint, 
/**
 * The affected region (the whole FOV for a full-lens tamper).
 */
region: BBox, mode: TamperMode, 
/**
 * Always `true`: tamper feeds the unlearnable never-benign floor.
 */
never_benign: boolean, 
/**
 * A monotonically rising assessment for this camera. Repeated tamper
 * **raises** it; it never decays on a tamper event.
 */
assessment: number, 
/**
 * Wall-clock (ms since UNIX epoch) the signal was emitted.
 */
emitted_unix_ms: bigint, };
