// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The five observable modes of camera interference (HARM_TAXONOMY §5).
 */
export type TamperMode = "obscuration" | "defocus" | "reframe" | "spray" | "illumination_collapse";
