// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";

export type TrackedObject = { track_id: bigint, label: string, confidence: number, bbox: BBox, 
/**
 * Raw detection bbox for THIS frame: `Some(d.bbox)` when the track
 * matched a detection on the current frame, `None` when the emitted
 * position is predicted-only. Unlike the EMA-smoothed `bbox` (kept
 * smooth for jitter-free live view), this is frame-aligned, so alert
 * snapshots and burned-in alert clips draw this box. See M_ALERT_CLIP.
 */
detection_bbox: BBox | null, 
/**
 * Frames since this track was first seen.
 */
age_frames: number, 
/**
 * Age of the track in milliseconds of frame time: this frame's
 * `captured_at` minus that of the frame the track was first seen on.
 */
age_ms: bigint, 
/**
 * Tracker + annotator outputs (motion.speed_class, dwell.zone_state, …).
 */
attributes: Record<string, unknown>, };
