// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BBox } from "./BBox";
import type { TrackLifecycle } from "./TrackLifecycle";

/**
 * M_PERF_CROWD F1 — minimal per-object payload for the lite
 * frame-metadata topic. `lifecycle` discriminates first-frame
 * tracks (so the overlay can draw a born indicator) from
 * established ones; it is derived from
 * [`TrackedObject::age_frames`] at construction time so the lite
 * topic never depends on the full motion-event lifecycle.
 */
export type TrackLite = { track_id: bigint, label: string, confidence: number, bbox: BBox, lifecycle: TrackLifecycle, };
